/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIInvokeWithParam */

#ifndef _Included_JNIInvokeWithParam
#define _Included_JNIInvokeWithParam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIInvokeWithParam
 * Method:    sayHelloWorld
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIInvokeWithParam_sayHelloWorld
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
