/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITestCpp */

#ifndef _Included_JNITestCpp
#define _Included_JNITestCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITestCpp
 * Method:    sayHelloWorld
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNITestCpp_sayHelloWorld
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
